// Code generated by "stringer -type=customError"; DO NOT EDIT.

package acres

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[minorFailure-0]
	_ = x[generalFailure-1]
	_ = x[criticalFailure-2]
}

const _customError_name = "minorFailuregeneralFailurecriticalFailure"

var _customError_index = [...]uint8{0, 12, 26, 41}

func (i customError) String() string {
	if i < 0 || i >= customError(len(_customError_index)-1) {
		return "customError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _customError_name[_customError_index[i]:_customError_index[i+1]]
}
